image: alpine
stages:
  - build
  - deploy
# before_script:
#   - apk add hugo

# run-build:
#   script:
#     - hugo
#     - ll public/

# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/hugo
# image: dettmering/hugo-build

compile:
  stage: build
  script:
    - apk add hugo
    - hugo
    - "ls -l public"
  artifacts:
    paths:
      - public
  only:
    - master

# test:
#   script:
#     - hugo
#   except:
#     - master

copy-to-bucket:
  stage: deploy
  image: python:latest
  script:
    - pip install awscli
    - aws s3 cp ./public s3://rdkn.eu/ --recursive --include "*"
