image: alpine

stages:
  - build
  - deploy

compile:
  stage: build
  script:
    - apk add hugo
    - hugo
    - "ls -l public"
  artifacts:
    paths:
      - public
  only:
    - master

copy-to-bucket:
  stage: deploy
  image: python:latest
  script:
    - pip install awscli
    - aws s3 cp ./public s3://rdkn.eu/ --recursive --include "*"
